In [2]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [3]:
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500


In [1]:
import numpy as np


In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# One single array

array([0., 0., 0., 0., 0.])

In [12]:
b=np.full(10,2.5)

In [14]:
b[1]= 20

In [15]:
print(b)

[ 2.5 20.   2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


In [7]:
a=np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
c=np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [10]:
d=np.full(20,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
arange1=np.arange(3,10)

In [18]:
arange1

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
arange1[1]=22

In [21]:
arange1

array([ 3, 22,  5,  6,  7,  8,  9])

In [22]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [24]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

### Multidiamentional array

In [26]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
m=np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

In [39]:
m[0,1]=20

In [40]:
m

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [43]:
m[ :2]

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [52]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [53]:
a=np.random.randint(-50, 100, size=(5,2))

In [54]:
a

array([[ 74,  66],
       [-13,  52],
       [-46,  57],
       [  1,  53],
       [-12, -17]])

# Elementwise operation

In [69]:
ab=np.arange(8)

In [70]:
ab

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
ab=ab*2

In [72]:
ab

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [73]:
cd=np.arange(8)

In [74]:
cd

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
ab>=cd

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [76]:
cd>=ab

array([ True, False, False, False, False, False, False, False])

In [77]:
ab[ab>cd]

array([ 2,  4,  6,  8, 10, 12, 14])

In [78]:
ab>2

array([False, False,  True,  True,  True,  True,  True,  True])

In [79]:
ab>7

array([False, False, False, False,  True,  True,  True,  True])

In [80]:
ab>12

array([False, False, False, False, False, False, False,  True])

In [81]:
ab.sum()

np.int64(56)

In [82]:
ab.mean()

np.float64(7.0)

In [86]:
std_div=ab.std()

In [87]:
ab.max()

np.int64(14)

In [88]:
ab.min()

np.int64(0)

In [89]:
std_div

np.float64(4.58257569495584)

In [103]:
u=np.array([1,2,3,4])

In [104]:
v=np.array([6,7,8,9])

In [105]:
u*v 7, 9, 11,13  6, 14, 24,36

array([ 6, 14, 24, 36])

In [106]:
u.shape[0]

4

In [107]:
v.shape[0]

4

In [116]:
def vect_mul(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    results=0.0
    for i in range(n):
        results+=u[i]*v[i]
    return results
    
    

In [117]:
print(vect_mul(u,v))

80.0


In [133]:
u1=np.array([[1,2,3,4,5],
            [5,6,7,8,5],
            [9,10,11,12,5],
            [13,14,15,16,5]])
v1=np.array([1,2,3,4,5])

In [135]:
v1.shape[0] 5,10

5

In [136]:
def vector_matrix_mul(u,v):
    assert u.shape[1]==v.shape[0]
    num_of_rows=u.shape[0]
    result=0
    for i in range(num_of_rows):
        result+=u[i]*v[i]
    return result
        
    

In [137]:
print(vector_matrix_mul(u1,v1))

[ 90 100 110 120  50]
